### PR TITLE
Updated sharing feature so it can send a url that matches the new web app

### PR DESCRIPTION
**Pull request by michaelharro**

### CODE REVIEW

**Comment by michaelharro** [comment]
Needs to be pushed to pod spec repo once approved.
If team desires a message to be added with the share link then it will need to be updated

**Comment by michaelharro** [comment]
@ryancarlson or @Lizzy_Randall could you take a look at this. It is part 1. Part 2 is on godtools-ios

**Comment by LizzyRandall** [comment]
@michaelharro  Fantastic :thumbsup:

**Comment by michaelharro** [comment]
thanks

**Pull request merged**
