### PR TITLE
Misc Bug fixes

### PR DESCRIPTION
**Pull request by michaelharro**
- Offers full support for all iPhone screen sizes.
  - fixes title heading font size
  - adds dynamic width of panel content
  - adds dynamic width of labels and images on a page
- Offers long term solution for amharic and other languages apple doesn't support
  - moved some default styling to a new GTStyle class
    - moved all font names
    - moved all default colors
  - removed GTPageInterpreterAmharic. Now GTInterpreter factory will return a GTPageInterpreter object with the appropriate GTStyle object injected into it. Now we just maintain one interpreter class.

### CODE REVIEW

**Comment by michaelharro** [comment]
@ryancarlson or @LizzyRandall could you review this?

**Comment by ryancarlson** [comment]
@LizzyRandall Can you review this please?

**Comment by LizzyRandall** [comment]
@ryancarlson @michaelharro I'll review it, the github email must have been buried while I was gone!

**Comment by LizzyRandall** [comment]
@michaelharro I asked three questions, one was a slight concern since something is getting passed in and not used, the others are for curiosity sake. Other than those three, looks good :+1:

**Comment by LizzyRandall** [comment]
I got all my questions explained, :+1: looks good.

**Comment by michaelharro** [comment]
cool, thanks.

**Pull request merged**
